-- 코드를 입력하세요
SELECT m.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, "%Y-%m-%d") 
FROM MEMBER_PROFILE m
JOIN REST_REVIEW r ON m.MEMBER_ID = r.MEMBER_ID
WHERE (SELECT COUNT(r.REVIEW_ID) FROM REST_REVIEW WHERE MEMBER_ID = m.MEMBER_ID)
    = (SELECT MAX(cnt) FROM (SELECT COUNT(REVIEW_ID) AS cnt
                            FROM REST_REVIEW
                            GROUP BY MEMBER_ID) count_table)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;